[package]
name = "vi"
version = "0.3.2"
authors = ["Nguyễn Việt Hưng <viethungax@gmail.com>"]
edition = "2018"
description = "An input method library for vietnamese IME"

homepage = "https://github.com/ZeroX-DG/vi-rs/"
repository = "https://github.com/ZeroX-DG/vi-rs.git"
license-file = "LICENSE"

keywords = ["vietnamese", "ime", "vi"]
categories = ["text-processing"]

[dependencies]
regex = "1.3.1"
phf = { version = "0.11", features = ["macros"] }

[dev-dependencies]
insta = "1.26"
cargo-insta = "1.26.0"
serde = "1.0"
