[package]
name = "vi-rs"
version = "0.1.0"
authors = ["Nguyễn Việt Hưng <hunggarena12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target."cfg(target_os = \"linux\")".dependencies]
evdev = { version = "0.10.1" }
uinput = { version = "0.1.3" }

[dependencies]
regex = "1.3.1"
phf = { version = "0.8", features = ["macros"] }
